[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bayesian_learning"
version = "0.1.0"
description = "A unified platform for learning Bayesian networks"
authors = [
    {name = "Leonardo Premutico"},
    {name = "Matteo Piscitello"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "joblib",
    "numba",
    "matplotlib",
    "pyagrum",
    "deap",
    "dagma",
    "torch",
    "pandas-stubs~=3.0.3",
    "seaborn>=0.13.2",
]

[project.urls]
"Homepage" = "https://github.com/LeonardoLeoo89/BayesianLearning"

[tool.setuptools.packages.find]
where = ["src"]
include = ["bayesian_learning*"]
