[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bayesian_learning"
version = "0.1.0"
description = "A unified platform for learning Bayesian networks"
authors = [
    {name = "Leonardo Premutico"},
    {name = "Matteo Piscitello"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "joblib",
    "numba",
    "matplotlib",
    "pyagrum",
    "deap",
    "dagma",
    "torch",
    "pandas-stubs~=3.0.3",
    "seaborn>=0.13.2",
    "py-tetrad",
    "gran-dag",
    "tabulate>=0.10.0",
    "jpype1>=1.7.1",
]

[project.urls]
"Homepage" = "https://github.com/LeonardoLeoo89/BayesianLearning"

[project.scripts]
bayesian-learn = "bayesian_learning.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
include = ["bayesian_learning*"]

[tool.uv.sources]
py-tetrad = { git = "https://github.com/cmu-phil/py-tetrad.git" }
gran-dag = { git = "https://github.com/LeonardoLeoo89/GraN-DAG.git", rev = "master" }

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.3.0",
    "sphinx>=9.0.4",
]
